# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: txnqueue-grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='txnqueue-grpc.proto',
  package='txnQueueInterface',
  syntax='proto3',
  serialized_pb=_b('\n\x13txnqueue-grpc.proto\x12\x11txnQueueInterface\"6\n\x07txndata\x12\r\n\x05txnid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0e\n\x06weight\x18\x03 \x01(\x05\";\n\x0btxnresponse\x12\x12\n\nretmessage\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1e\n\nretmessage\x12\x10\n\x08rmessage\x18\x01 \x01(\t\"+\n\ntxnrequest\x12\r\n\x05txnid\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x05\x32\xb5\x01\n\x11txnQueueInterface\x12L\n\rsetTxnInQueue\x12\x1a.txnQueueInterface.txndata\x1a\x1d.txnQueueInterface.retmessage\"\x00\x12R\n\x0fgetTxnFromQueue\x12\x1d.txnQueueInterface.txnrequest\x1a\x1e.txnQueueInterface.txnresponse\"\x00\x62\x06proto3')
)




_TXNDATA = _descriptor.Descriptor(
  name='txndata',
  full_name='txnQueueInterface.txndata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txnid', full_name='txnQueueInterface.txndata.txnid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='txnQueueInterface.txndata.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='txnQueueInterface.txndata.weight', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=96,
)


_TXNRESPONSE = _descriptor.Descriptor(
  name='txnresponse',
  full_name='txnQueueInterface.txnresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retmessage', full_name='txnQueueInterface.txnresponse.retmessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='txnQueueInterface.txnresponse.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='txnQueueInterface.txnresponse.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=157,
)


_RETMESSAGE = _descriptor.Descriptor(
  name='retmessage',
  full_name='txnQueueInterface.retmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rmessage', full_name='txnQueueInterface.retmessage.rmessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=189,
)


_TXNREQUEST = _descriptor.Descriptor(
  name='txnrequest',
  full_name='txnQueueInterface.txnrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txnid', full_name='txnQueueInterface.txnrequest.txnid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='txnQueueInterface.txnrequest.weight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['txndata'] = _TXNDATA
DESCRIPTOR.message_types_by_name['txnresponse'] = _TXNRESPONSE
DESCRIPTOR.message_types_by_name['retmessage'] = _RETMESSAGE
DESCRIPTOR.message_types_by_name['txnrequest'] = _TXNREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

txndata = _reflection.GeneratedProtocolMessageType('txndata', (_message.Message,), dict(
  DESCRIPTOR = _TXNDATA,
  __module__ = 'txnqueue_grpc_pb2'
  # @@protoc_insertion_point(class_scope:txnQueueInterface.txndata)
  ))
_sym_db.RegisterMessage(txndata)

txnresponse = _reflection.GeneratedProtocolMessageType('txnresponse', (_message.Message,), dict(
  DESCRIPTOR = _TXNRESPONSE,
  __module__ = 'txnqueue_grpc_pb2'
  # @@protoc_insertion_point(class_scope:txnQueueInterface.txnresponse)
  ))
_sym_db.RegisterMessage(txnresponse)

retmessage = _reflection.GeneratedProtocolMessageType('retmessage', (_message.Message,), dict(
  DESCRIPTOR = _RETMESSAGE,
  __module__ = 'txnqueue_grpc_pb2'
  # @@protoc_insertion_point(class_scope:txnQueueInterface.retmessage)
  ))
_sym_db.RegisterMessage(retmessage)

txnrequest = _reflection.GeneratedProtocolMessageType('txnrequest', (_message.Message,), dict(
  DESCRIPTOR = _TXNREQUEST,
  __module__ = 'txnqueue_grpc_pb2'
  # @@protoc_insertion_point(class_scope:txnQueueInterface.txnrequest)
  ))
_sym_db.RegisterMessage(txnrequest)



_TXNQUEUEINTERFACE = _descriptor.ServiceDescriptor(
  name='txnQueueInterface',
  full_name='txnQueueInterface.txnQueueInterface',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=237,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='setTxnInQueue',
    full_name='txnQueueInterface.txnQueueInterface.setTxnInQueue',
    index=0,
    containing_service=None,
    input_type=_TXNDATA,
    output_type=_RETMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getTxnFromQueue',
    full_name='txnQueueInterface.txnQueueInterface.getTxnFromQueue',
    index=1,
    containing_service=None,
    input_type=_TXNREQUEST,
    output_type=_TXNRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TXNQUEUEINTERFACE)

DESCRIPTOR.services_by_name['txnQueueInterface'] = _TXNQUEUEINTERFACE

# @@protoc_insertion_point(module_scope)
